#IFNDEF _EXAMPLESERVICE3_H__
#DEFINE _EXAMPLESERVICE3_H__

&& meaning of Action property in FILE_NOTIFY_INFORMATION structure
#DEFINE FILE_ACTION_ADDED				0x00000001
#DEFINE FILE_ACTION_REMOVED				0x00000002
#DEFINE FILE_ACTION_MODIFIED			0x00000003
#DEFINE FILE_ACTION_RENAMED_OLD_NAME	0x00000004
#DEFINE FILE_ACTION_RENAMED_NEW_NAME	0x00000005

&& rights for CreateFile
#DEFINE FILE_LIST_DIRECTORY	0x001

&& flags for CreateFile
#DEFINE CREATE_NEW			1
#DEFINE CREATE_ALWAYS		2
#DEFINE OPEN_EXISTING		3
#DEFINE OPEN_ALWAYS			4
#DEFINE TRUNCATE_EXISTING	5

#ENDIF && _EXAMPLESERVICE3_H__